# =========================
# TIPOS
# =========================

enum Plataforma {
    PS4
    PS5
    PC
    XBOXONE
    NINTENDO
}

type VideoJuegos {
    id: ID!
    cliente: Cliente!
    nombre: String!
    precio: Float!
    fecha_lanzamiento: String!
    genero: String!
    plataforma: Plataforma!
    edad: Int!
    isDeleted: Boolean!
}

type Cliente {
    id: ID!
    nombre: String!
    fecha_creacion: String!
    fecha_actualizacion: String!
    isDeleted: Boolean!
    videoJuegos: [VideoJuegos!]!
}

# =========================
# QUERIES
# =========================

type Query {
    videoJuegos: [VideoJuegos!]!
    videoJuegoById(id: ID!): VideoJuegos

    clientes: [Cliente!]!
    clienteById(id: ID!): Cliente
    clienteByNombre(nombre: String!): [Cliente!]!
}

