-- =========================
-- DROP TABLES (orden correcto)
-- =========================
drop table if exists user_roles cascade;
drop table if exists videojuegos cascade;
drop table if exists usuarios cascade;
drop table if exists clientes cascade;

-- =========================
-- CLIENTES
-- =========================
create table clientes (
      id bigint generated by default as identity primary key,
      nombre varchar(100) not null unique,
      fecha_creacion timestamp default current_timestamp,
      fecha_actualizacion timestamp default current_timestamp,
      is_deleted boolean default false
);

-- =========================
-- USUARIOS
-- =========================
create table usuarios (
      id bigint generated by default as identity primary key,
      nombre varchar(255) not null,
      apellidos varchar(255) not null,
      username varchar(255) not null unique,
      email varchar(255) not null unique,
      password varchar(255) not null,
      is_deleted boolean default false,
      created_at timestamp default current_timestamp not null,
      updated_at timestamp default current_timestamp not null,
      cliente_id bigint not null,
      constraint fk_usuario_cliente
          foreign key (cliente_id)
              references clientes(id)
              on delete cascade
);

-- =========================
-- USER ROLES
-- =========================
create table user_roles (
        user_id bigint not null,
        roles varchar(10) not null,
        constraint chk_role check (roles in ('USER','ADMIN')),
        constraint fk_user_roles_usuario
            foreign key (user_id)
                references usuarios(id)
                on delete cascade,
        primary key (user_id, role)
);

-- =========================
-- VIDEOJUEGOS
-- =========================
create table videojuegos (
         id bigint generated by default as identity primary key,
         cliente_id bigint not null,
         nombre varchar(55) not null,
         precio decimal(10,2) not null,
         fecha_lanzamiento date,
         genero varchar(50) not null,
         plataforma varchar(10) not null,
         edad int not null,
         is_deleted boolean default false,
         constraint chk_plataforma
             check (plataforma in ('PC','PS5','PS4','XBOXONE','NINTENDO')),
         constraint fk_videojuego_cliente
             foreign key (cliente_id)
                 references clientes(id)
                 on delete cascade
);


INSERT INTO CLIENTES (nombre) VALUES ('Juan'),
                                     ('Maria'),
                                     ('Carlos'),
                                     ('Ana Martinez'),
                                     ('Luis');


INSERT INTO VIDEOJUEGOS (cliente_id, nombre, precio, fecha_lanzamiento, genero, plataforma, edad)
VALUES (1, 'The Legend of Zelda: Breath of the Wild', 59.99, '2017-03-03', 'Aventura', 'NINTENDO', 12),
       ( 2, 'God of War', 49.99, '2018-04-20', 'Accion', 'PS4', 18),
       ( 3, 'Red Dead Redemption 2', 39.99, '2018-10-26', 'Accion/Aventura', 'XBOXONE', 18),
       ( 4, 'Minecraft', 26.95, '2011-11-18', 'Sandbox', 'PS5', 7),
       ( 5, 'Fortnite', 10.00, '2017-07-21', 'Battle Royale', 'PC', 12);



INSERT INTO USUARIOS (nombre, apellidos, username, email, password, cliente_id)
VALUES ('Juan', 'Perez', 'admin', 'admin@prueba.net',
        '$2a$10$vPaqZvZkz6jhb7U7k/V/v.5vprfNdOnh4sxi/qpPRkYTzPmFlI9p2', 1);

insert into USER_ROLES (user_id, roles)
values (1, 'USER'),
       (1, 'ADMIN');

insert into USUARIOS (nombre, apellidos, username, email, password, cliente_id)
values ('Maria',
        'Gomez',
        'mariaGomez',
        'usuario@prueba',
        '$2a$10$TxZ6mmE0GTA3duo/aththOL1KjuNcU.GHnr2jV7mmpqHdrom2Egvu',
        2);

insert into USER_ROLES (user_id, roles)
values (2, 'USER');

insert into USUARIOS (nombre, apellidos, username, email, password, cliente_id)
values ('Test', 'Test Test', 'test', 'test@prueba.net',
        '$2a$10$Pd1yyq2NowcsDf4Cpf/ZXObYFkcycswqHAqBndE1wWJvYwRxlb.Pu',3);

insert into USER_ROLES (user_id, roles)
values (3, 'USER');


-- =========================
-- CLIENTE ADMINISTRADOR
-- =========================
insert into CLIENTES (nombre)
values ('Marius');

-- =========================
-- USUARIO ADMINISTRADOR
-- =========================
insert into USUARIOS (nombre, apellidos, username, email, password, cliente_id)
values (
           'Marius',
           'Puruguay',
           'marius29',
           'marius@prueba.com',
           '$2a$10$TxZ6mmE0GTA3duo/aththOL1KjuNcU.GHnr2jV7mmpqHdrom2Egvu',
           (select id from CLIENTES where nombre = 'Marius')
       );

-- =========================
-- ROLES USER
-- =========================
insert into USER_ROLES (user_id, roles)
values
    ((select id from USUARIOS where username = 'marius29'), 'USER'),
    ((select id from USUARIOS where username = 'marius29'),'ADMIN');


insert into clientes (nombre) values ('Patrick');

insert into USUARIOS (nombre, apellidos, username, email, password, cliente_id)
values (
           'Patrick',
           'Smith',
           'patrickU',
           'patrick@prueba.com',
           '$2a$10$VUpWkhTCIFhCRz3u8C7PROOLYix.J3cL7vpMchw3pW59CGaf5bKF.',
          (select id from CLIENTES where nombre = 'Patrick')
         );

insert into USER_ROLES (user_id, roles)
values
    ((select id from USUARIOS where username = 'patrickU'), 'USER');


-- =========================
-- ROLES USER SIN VIDEOJUEGOS
-- =========================
insert into clientes(nombre) values ('Daniel');

insert into USUARIOS (nombre, apellidos, username, email, password, cliente_id)
values (
           'Daniel',
           'Jimenez',
           'Daniel1',
        'daniel@prueba.com',
           '$2a$10$Hin7D0eTRx1oh7STkzXk8Oz7rYjX.aJiLsRql5RH65SizLyvsTXki',
            (select id from CLIENTES where nombre = 'Daniel')
        );

insert into USER_ROLES (user_id, roles)
values
    ((select id from USUARIOS where username = 'Daniel1'), 'USER');


INSERT INTO VIDEOJUEGOS (cliente_id, nombre, precio, fecha_lanzamiento, genero, plataforma, edad)
VALUES
-- Cliente 1 (Juan)
(1, 'Super Mario Odyssey', 49.99, '2017-10-27', 'Plataformas', 'NINTENDO', 7),
(1, 'Metroid Dread', 59.99, '2021-10-08', 'Accion', 'NINTENDO', 12),
(1, 'Animal Crossing: New Horizons', 54.99, '2020-03-20', 'Simulacion', 'NINTENDO', 3),

-- Cliente 2 (Maria)
(2, 'Horizon Zero Dawn', 39.99, '2017-02-28', 'Accion/Aventura', 'PS4', 16),
(2, 'Spider-Man', 44.99, '2018-09-07', 'Accion', 'PS4', 12),
(2, 'The Last of Us Part II', 59.99, '2020-06-19', 'Accion/Aventura', 'PS4', 18),

-- Cliente 3 (Carlos)
(3, 'Halo Infinite', 59.99, '2021-12-08', 'Shooter', 'XBOXONE', 16),
(3, 'Forza Horizon 5', 49.99, '2021-11-09', 'Carreras', 'XBOXONE', 3),
(3, 'Gears 5', 39.99, '2019-09-10', 'Shooter', 'XBOXONE', 18),

-- Cliente 4 (Ana Martinez)
(4, 'FIFA 23', 69.99, '2022-09-30', 'Deportes', 'PS5', 3),
(4, 'NBA 2K24', 69.99, '2023-09-08', 'Deportes', 'PS5', 3),
(4, 'Gran Turismo 7', 59.99, '2022-03-04', 'Carreras', 'PS5', 3),

-- Cliente 5 (Luis)
(5, 'League of Legends', 0.00, '2009-10-27', 'MOBA', 'PC', 12),
(5, 'Valorant', 0.00, '2020-06-02', 'Shooter', 'PC', 16),
(5, 'Cyberpunk 2077', 49.99, '2020-12-10', 'RPG', 'PC', 18),

-- Cliente 6 (Marius)
(6, 'Elden Ring', 59.99, '2022-02-25', 'RPG', 'PC', 16),
(6, 'Dark Souls III', 39.99, '2016-04-12', 'RPG', 'PC', 16),
(6, 'Sekiro: Shadows Die Twice', 49.99, '2019-03-22', 'Accion', 'PC', 18),

-- Cliente 7 (Patrick)
(7, 'The Witcher 3', 29.99, '2015-05-19', 'RPG', 'PC', 18),
(7, 'Assassin’s Creed Valhalla', 39.99, '2020-11-10', 'Accion/Aventura', 'PC', 18),
(7, 'Starfield', 69.99, '2023-09-06', 'RPG', 'PC', 16),

-- Extras repartidos
(2, 'Crash Bandicoot 4', 34.99, '2020-10-02', 'Plataformas', 'PS4', 7),
(3, 'Ori and the Will of the Wisps', 29.99, '2020-03-11', 'Aventura', 'XBOXONE', 7),
(1, 'Kirby and the Forgotten Land', 49.99, '2022-03-25', 'Plataformas', 'NINTENDO', 7);



