
spring.application.name=AplicacionVideoJuegos


server.port=${PORT:3005}

api.version=${API_VERSION:v1}

server.error.include-message=always

logging.level.com.example.aplicacionvideojuegos=DEBUG

## Base de datos de desarrollo puede ser H2
# En fichero embebida o en memoria, tú eliges
spring.datasource.url= jdbc:h2:mem:videojuegospirest

# Usuario y contraseña de la base de datos
spring.datasource.username=sa
#spring.datasource.password=password

# Habilitamos la consola de H2
# En nuestro caso http://localhost:3000/h2-console
spring.h2.console.enabled=true


# Habilitamos que cargue los datos de prueba en la base de datos
# estos datos los carga del fichero data.sql del directorio resources
spring.jpa.defer-datasource-initialization=true

# Habilitamos la creación de la base de datos en cada arranque
spring.jpa.hibernate.ddl-auto=create-drop

# Habilitamos la carga de datos de prueba en cada arranque
spring.sql.init.mode=always

# Habilitamos el dialecto de H2
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect


## SQL
# Habilitamos los mensajes sql en el log para ver las consultas
spring.jpa.show-sql=true


# Formatea la salida SQL para que se lea mejor en la consola
spring.jpa.properties.hibernate.format_sql=true

## Logging
# Para activar los mensajes nivel DEBUG en las clases es.carlosgs.tarjetas, por ejemplo
logging.level.es.carlosgs.tarjetas=DEBUG
# Para ver los valores de los parámetros consultas Hibernate 6 \ Spring Boot 3
logging.level.org.hibernate.orm.jdbc.bind=TRACE