
## Desarrollo
# spring.profiles.active=dev


## Base de datos de desarrollo puede ser H2
# En fichero embebida o en memoria, t� eliges
spring.datasource.url= jdbc:h2:mem:videojuegospirest

# Usuario y contrase�a de la base de datos
spring.datasource.username=sa
#spring.datasource.password=password

# Habilitamos la consola de H2
# En nuestro caso http://localhost:3005/h2-console
spring.h2.console.enabled=true


# Habilitamos que cargue los datos de prueba en la base de datos
# estos datos los carga del fichero data.sql del directorio resources
spring.jpa.defer-datasource-initialization=true

# Habilitamos la creaci�n de la base de datos en cada arranque
spring.jpa.hibernate.ddl-auto=create-drop

# Habilitamos la carga de datos de prueba en cada arranque
spring.sql.init.mode=always

# Habilitamos el dialecto de H2
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.sql.init.continue-on-error=false

## SQL
# Habilitamos los mensajes sql en el log para ver las consultas
spring.jpa.show-sql=true


# Formatea la salida SQL para que se lea mejor en la consola
spring.jpa.properties.hibernate.format_sql=true

## Logging


# Para ver los valores de los par�metros consultas Hibernate 6 \ Spring Boot 3
logging.level.org.hibernate.orm.jdbc.bind=TRACE
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE


## PEBBLE Template Engine
pebble.cache=false

## Configuración DevTools
spring.devtools.restart.enabled=false
spring.devtools.restart.additional-paths=src/main/java,src/main/resources
spring.devtools.restart.exclude=static/**,public/**
spring.devtools.livereload.enabled=true
spring.devtools.livereload.port=35729