
## Globales
spring.application.name=AplicacionVideoJuegos

application.title=${APPLICATION_TITLE:Aplicacion de Videojuegos REST con Spring Boot}
application.version=${APPLICATION_VERSION:1.0.0}


server.port=${PORT:3005}

api.version=${API_VERSION:v1}

#Perfil activo
spring.profiles.active=dev

server.error.include-message=always




## JWT
# Configuraci�n de secreto y tiempo de token en segundos (86400 = 24 horas) pon el que quieras
jwt.secret=BabyNoMeLlameQueYoEstoyOcup�OlvidandoTusMaleYaDecid�QueEstaNocheSeSaleConToaMisMotomamiConTodaNisGyales
# expiration in seconds (24*60*60 = 24 horas)
jwt.expiration=86400


## SWAGGER
# Habilitamos swagger, quitar en producci�n
springdoc.swagger-ui.enabled=true

## GRAPHQL
# Habilitar GraphiQL (playground web)
spring.graphql.graphiql.enabled=true
spring.graphql.graphiql.path=/graphiql

# Configuración del endpoint GraphQL
spring.graphql.http.path=/graphql

## PEBBLE Template Engine
pebble.suffix=.peb.html
pebble.template-loader-path=classpath:/templates/
pebble.charset=UTF-8

## MENSAJES (i18n)
spring.messages.basename=messages
spring.messages.encoding=UTF-8
