/*
-- Borra la tabla si existe
drop table if exists TARJETAS;
-- Crea la tabla TARJETAS
create table TARJETAS (
    id bigint generated by default as identity PRIMARY KEY,
    numero varchar(19) not null,
    cvc varchar(3) not null,
    fecha_caducidad date not null,
    titular varchar(50) not null,
    saldo float(53) not null,
    is_deleted boolean default false,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP not null,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP not null,
    uuid uuid not null unique
);
*/

INSERT INTO CLIENTES (nombre) VALUES ('Juan Perez'),
                                     ('Maria Gomez'),
                                     ('Carlos Sanchez'),
                                     ('Ana Martinez'),
                                     ('Luis Rodriguez');



INSERT INTO VIDEOJUEGOS (cliente_id, nombre, precio, fecha_lanzamiento, genero, plataforma, edad)
VALUES (1, 'The Legend of Zelda: Breath of the Wild', 59.99, '2017-03-03', 'Aventura', 'NINTENDO', 12),
       ( 2, 'God of War', 49.99, '2018-04-20', 'Accion', 'PS4', 18),
       ( 3, 'Red Dead Redemption 2', 39.99, '2018-10-26', 'Accion/Aventura', 'XBOXONE', 18),
       ( 4, 'Minecraft', 26.95, '2011-11-18', 'Sandbox', 'PS5', 7),
       ( 5, 'Fortnite', 0.00, '2017-07-21', 'Battle Royale', 'PC', 12);