
#VideoJuegos

label.videojuegos.empty=No se han encontrado videojuegos
label.videojuegos.nombre=Nombre
label.videojuegos.plataforma=Plataforma
label.videojuegos.detalle=Detalles del videojuego
videojuegos.search=Buscar

#Barra de Navegación
nav.home=Inicio
nav.login=Conexión
nav.new.videojuegos=Nuevo Videojuego
