
#VideoJuegos

label.videojuegos.empty=No se han encontrado videojuegos
label.videojuegos.nombre=Nombre
label.videojuegos.plataforma=Plataforma
label.videojuegos.detalle=Detalles del videojuego
videojuegos.search=Buscar

#Barra de Navegación
nav.home=Inicio
nav.login=Conexión
nav.logout=Cerrar Sesión
nav.new.videojuegos=Nuevo Videojuego
error.404= Recurso no encontrado

@Autenticación
auth.login=Iniciar Sesión
auth.register=Registrarse
auth.logout=Cerrar Sesión
auth.email=Email
auth.username=Usuario
auth.password=Contraseña
auth.remember=Recordarme
auth.forgot.password=¿Olvidaste tu contraseña?


