### getAll (debería devolver todas las tarjetas al venir la petición de un origen autorizado)
GET http://localhost:3005/api/v1/videoJuegos
Origin: http://mifrontend.es

### getAll (debería devolver un 403 al no venit la petición de un origen autorizado)
GET http://localhost:3005/api/v1/videoJuegos
Origin: http://otrodominio.es