### Authorization by token, part 1. Retrieve and save token.

### Proceso de Login
###
POST http://localhost:3005/api/v1/auth/signin
Content-Type: application/json

{
  "username": "admin",
  "password": "Admin1"
}

> {% client.global.set("auth_token", response.body.token); %}

### Authorization by token, part 2. Use token to authorize.



### Proceso de Registro
POST http://localhost:3005/api/v1/auth/signup
Content-Type: application/json

{
  "nombre": "Daniel",
  "apellidos": "Jimenez",
  "username": "Daniel1",
  "email": "daniel@prueba.com",
  "password": "12345",
  "passwordComprobacion": "12345"
}