
drop table if exists videojuegos;
drop table if exists clientes;

create table clientes (
      id bigint generated by default as identity primary key,
      nombre varchar(100) not null unique,
      fecha_creacion timestamp default current_timestamp,
      fecha_actualizacion timestamp default current_timestamp,
      is_deleted boolean default false
);

create table VIDEOJUEGOS(
    id                INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id        INT REFERENCES CLIENTES(id),
    nombre            VARCHAR(55) NOT NULL,
    precio            DECIMAL(10,2) NOT NULL,
    fecha_lanzamiento  DATE,
    genero            VARCHAR(50) NOT NULL,
    plataforma        VARCHAR(10) CHECK (plataforma in ('PC', 'PS5','PS4', 'XBOXONE', 'NINTENDO')) NOT NULL,
    edad              INT NOT NULL,
    is_delete          BOOLEAN   DEFAULT FALSE
);

--Foreign Keys
alter table VIDEOJUEGOS
    add constraint fk_videojuegos_clientes_id
    foreign key (cliente_id) references CLIENTES(id) on delete cascade;

