
drop table if exists VIDEOJUEGOS;
drop table if exists CLIENTES;

create table CLIENTES (
      id bigint generated by default as identity primary key,
      nombre varchar(100) not null unique,
      fecha_creacion timestamp default current_timestamp,
      fecha_actualizacion timestamp default current_timestamp,
      is_deleted boolean default false
);

create table VIDEOJUEGOS(
    id                bigint generated by default as identity PRIMARY KEY,
    cliente_id        bigint,
    nombre            VARCHAR(55) NOT NULL,
    precio            DECIMAL(10,2) NOT NULL,
    fecha_lanzamiento  DATE,
    genero            VARCHAR(50) NOT NULL,
    plataforma        VARCHAR(10) CHECK (plataforma in ('PC', 'PS5','PS4', 'XBOXONE', 'NINTENDO')) NOT NULL,
    edad              INT NOT NULL,
    is_deleted          BOOLEAN   DEFAULT FALSE
);

--Foreign Keys
alter table if exists VIDEOJUEGOS
    add constraint FK_VIDEOJUEGOS_CLIENTES_CLIENTE_ID
    foreign key (cliente_id) references clientes(id);

