
-- Limpiar tablas antes de cada test
drop table if exists CLIENTES;
drop table  if exists VIDEOJUEGOS;

-- Crear tablas
create table CLIENTES(
    id                 INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre             VARCHAR(100) NOT NULL,
    fechaCreacion      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    fechaActualizacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    isDelete           BOOLEAN DEFAULT FALSE,
);

create table VIDEOJUEGOS(
    id                INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id        INT REFERENCES CLIENTES(id),
    nombre            VARCHAR(55) NOT NULL,
    precio            DECIMAL(10,2) NOT NULL,
    fechaLanzamiento  DATE,
    genero            VARCHAR(50) NOT NULL,
    plataforma        VARCHAR(10) CHECK (plataforma in ('PC', 'PS5','PS4', 'XBOXONE', 'NINTENDO')) NOT NULL,
    edad              INT NOT NULL,
    isDelete          BOOLEAN   DEFAULT FALSE,
);

--Foreign Keys
alter table VIDEOJUEGOS
    add constraint fk_videojuegos_clientes_id
    foreign key (cliente_id) references CLIENTES(id) on delete cascade;

